name: workflow commands
on: [push]

jobs:
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Display an Error message
              run: echo "::error::This is an error message"
            - name: Display an Error message with params
              run: echo "::error title=Error title, file=app.js, line=2, endLine=3, col=5, endColumn=7::This is an error message"
            - name: Display a warning message with params
              run: echo "::warning title=Warning title, file=app.js, line=2, endLine=3, col=5, endColumn=7::This is an error message"
            - name: Display a debug message with params
              run: echo "::debug title=Debug title, file=app.js, line=2, endLine=3, col=5, endColumn=7::This is an error message"
            - name: Display a Notice message with params
              run: echo "::notice title=Notice title, file=app.js, line=2, endLine=3, col=5, endColumn=7::This is an error message"
            - name: Display a group message
              run: |
                echo "::group::My group title"
                echo "inside group"
                echo "::endgroup::"
            - name: Mask Message
              run: echo "::add-mask::SecretString"
            - name: output mask message
              run: echo "SecretString"